### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by toddrme2178** [pyside/Shiboken#77]
FindPython3Libs.cmake currently only support python 3.4.  Python 3.5, however, is the most recent release.  Would it be possible to support python 3.5 as well?

**Comment by thopiekar** [comment]
Haven't tested to build Python 3.5 with shiboken, but I added a PR for an addition that needs to be done, so FindPython3Libs.cmake can find python3.5.
Please test https://github.com/PySide/Shiboken/pull/79 and give feedback there if it works.

**Comment by gdude2002** [comment]
While that PR has been effectively merged, and the other 3.5 tickets appear to be have been closed as "done", it's worth noting that Shiboken is checking for `subprocess.mswindows` - which doesn't exist in Python 3.5. 

It ended up being renamed to `subprocess._mswindows`; I'm not sure why you guys are checking for this, but if it's to check whether the platform is Windows.. There are proper ways to do so.

**Comment by siddharthist** [comment]
Does Shiboken support Python 3.6?

**Comment by gdude2002** [comment]
Unless this issue has been fixed, no. I haven't had a chance to check.

**Comment by gdude2002** [comment]
Considering the last commit was October last year, I'd say that no changes have been made.

**Comment by siddharthist** [comment]
@gdude2002 Sorry, I should've investigated that myself! Thanks for the quick response.
